application:
  locale: ru_RU

spring:
  shell:
    interactive:
      enabled: false

  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:testdb
    initialization-mode: always

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none

  liquibase:
    enabled: true
    change-log: classpath:liquibase/rootChangeLog.xml

management:
  endpoints:
    web:
      exposure:
        include: "health,metrics,logfile"
  endpoint:
    health:
      show-details: always
  health:
    defaults:
      enabled: true

logging:
  file:
    path: C:\
    name: LibraryTools.log